### ISSUE TITLE
Revisit Data stored in repo/expected to be generated by gui user

### ISSUE THREAD

**Issue by zbuckley** [gwu-data-mining-finalproject/Final-Project-GroupX#11]
Believe so far we should only have the following provided by the initial download from github.
1)
zipped original data file from netflix
movie metadata file from netflix
2)
preprocessed downsampled data: downsampled.csv
3)
preprocessed user distance calculations clustering data
4)
???

**Comment by PedroUria** [comment]
The clustering is a problem because it takes too long for it to be generated by the user... If we don't store it on the GitHub, how do we continue with the rest of the project? We could put an option on the GUI: Use our pre-clustered data, or cluster your own data based on you own random downsampling, but wait one and a half hours xD. We do have all the distances so we could let the user change the threshold (right now at 0.04).

**Comment by PedroUria** [comment]
And I don't know about movie clustering, we need to discuss that again, better in person.

**Comment by zbuckley** [comment]
movie clustering out based on most recent conversation. 
We were able to reduce the runtime on the modeling code yesterday. 
Bet we can do something similar with the clustering if you're up for it. 
May not get as good improvements... but it's worth a look.

**Comment by QuirkyDataScientist1978** [comment]
Agreed - we need to look at your clustering again. With what was optimized last night wouldn't the clustering run faster now?

**Comment by PedroUria** [comment]
Done with it, it was running pretty fast. It's just that there are a ton of users.
